---
exclude:
  - ClickHouse/clickhouse.github.io
  - ClickHouse/llvm
  - ClickHouse/protobuf
  - ClickHouse/ssl
  - ClickHouse/libgsasl
  - ClickHouse/libuv
  - ClickHouse/UnixODBC
  - ClickHouse/grpc
  - cilium/busybox
  - istio/old_vendor-istio_repo
  - openebs/openebs-docs
  - chaos-mesh/toda-glibc
  - envoyproxy/envoy-website
  - cockroachdb/vendored
  - cockroachdb/cockroach-gen
  - cockroachdb/c-protobuf
  - cockroachdb/c-rocksdb
  - cockroachdb/c-jemalloc
  - cockroachdb/c-snappy
  - cockroachdb/c-lz4
  - zephyrproject-rtos/hal_nxp
  - zephyrproject-rtos/hal_stm32
  - zephyrproject-rtos/hal_silabs
  - zephyrproject-rtos/hal_espressif
  - zephyrproject-rtos/newlib-cygwin
  - zephyrproject-rtos/hal_st
  - zephyrproject/lipstick2
include:
  repos:
    - torvalds/linux
    - VKCOM/statshouse
    - VKCOM/VKUI
    - pixie-io/pixie
    - falcosecurity/falco
    - apache/mesos
    - apache/aurora
    - uber/peloton
    - Netflix/titus-executor
    - Netflix/titus-control-plane
    - vitalif/vitastor
    - LINBIT/linstor-server
    - uber/kraken
    - containers/podman
    - facebook/react
    - vuejs/vue
    - tensorflow/tensorflow
    - golang/go
    - python/cpython
    - rust-lang/rust
    - tikv/tikv
    - dragonflyoss/Dragonfly2
    - elastic/elasticsearch
    - elastic/beats
    - elastic/logstash
    - ziglang/zig
    - matplotlib/matplotlib
    - pallets/flask
    - django/django
    - nodejs/node
    - jquery/jquery
    - godotengine/godot
    - denoland/deno
    - tauri-apps/tauri
    - alacritty/alacritty
    - firecracker-microvm/firecracker
    - meilisearch/meilisearch
  orgs:
    - ClickHouse
    - kata-containers
    - siderolabs
    - m3db
    - grafana
    - VictoriaMetrics
    - vectordotdev
    - docker
    - moby
    - go-faster
    - gotd
    - ogen-go
    - ydb-platform
    - ytsaurus
    - ten-nancy
    - cockroachdb
    - netdata
    - zephyrproject-rtos
    - metrico
    - gravity-ui
